### ISSUE TITLE
scRNA-seq data normalization for PCA

### ISSUE THREAD

**Issue by mbabadi** [cellarium-ai/cellarium-ml#11]
PCA expects Gaussian distributed data, whereas raw scRNA-seq data is integral. The heuristic in the field is to apply the following transformations:

$\ell_n = \sum_g X_{ng}$
$y_{ng} = \log(1 + C \times X_{ng} / \ell_n)$
$z_{ng} = (y_{ng} - \mu_g) / \sigma_g$

where $C = 10,000$ is a "pseudocount", and:

$\mu_g = \frac{1}{N}\sum_n y_{ng}$
$\sigma^2_g = \frac{1}{N}\sum_n (y_{ng} - \mu_g)^2$

Feature whitening, i.e. dividing by $\sigma_g$, is considered "optional" and is sometimes skipped (reasoning: a more variable gene is likely to be a more biologically informative gene, and we should not throw out that information).

This normalization recipe introduces two problems:
- The recipe is an integral part of the PCA transformation of the data, and applying a learned PCA transformation to user's data requires the knowledge of the parameters of this normalization recipe: $C$, $\mu_g$, and $\sigma_g$.
- $\mu_g$ and $\sigma_g$ must be calculated from full batch data

The first problem is easy to solve:  we create a `LogNormalizationTransform` module which is passed the PCA module. The parameters of the transformation naturally become part of the state of the PCA module.

The second problem, i.e estimation of full batch $\mu_g$ and $\sigma_g$, can be done in 3 different ways:
- A single-pass estimation using BigQuery; $\mu_g$ and $\sigma_g$ would then be written to the `.var` metadata, and `C` to the `.uns` dictionary.
- A single-pass estimation from AnnData chunks; this can be parallelized, but will be inevitably slower than the previous approach and add one extra epoch of data loading.
- Online estimation: we can use ideas from `BatchNorm` (and `SyncBatchNorm` for parallelization) to estimate $\mu_g$ and $\sigma_g$ from minibatches; we can also increase the exponential moving average (EMA) window as training proceeds to stabilize the estimates.

**Comment by ordabayevy** [comment]
I added the `LogNormalize` transform in #15. @mbabadi isn't it a bit redundant that we have the mean parameter both in `LogNormalize` and `ProbabilisticPCA`?
