### ISSUE TITLE
Logistic Regression train doesn't work with multiple GPUs

### ISSUE THREAD

**Issue by fedorgrab** [cellarium-ai/cellarium-ml#112]
When I start a training script with multiple GPUs, I get:

```
File "/home/user/micromamba/lib/python3.10/site-packages/cellarium/ml/utilities/data.py", line 194, in categories_to_codes
AttributeError: 'numpy.ndarray' object has no attribute 'cat'
```

**Comment by mbabadi** [comment]
Huh interesting-- good detective work! I suggest forking `AnnCollection` and fixing it for `cellarium-ml` (higher priority, given our tight timeline), and also working with `anndata` devs to fix it upstream (lower priority).
