### ISSUE TITLE
scvi - implement `reset_parameters()`

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#146]
And also figure out what it's doing now, when we just `pass`.

**Comment by sjfleming** [comment]
Potentially see here for reference

https://github.com/cellarium-ai/cellarium-ml/blob/fc8a2d079222daee6b7222f952e43c44e66ca931/cellarium/ml/models/cellarium_gpt.py#L557-L576

**Comment by sjfleming** [comment]
Also see another example here for a different model
https://github.com/cellarium-ai/cellarium-ml/blob/5495aa899e418aac9be12479a7d0b073ee65c791/cellarium/ml/models/probabilistic_pca.py#L97-L103

**Comment by ImXman** [comment]
`        def reset_parameters(self) -> None:
            # pass
            self.z_encoder.encoder.fc_layers.apply(weights_init)
            self.z_encoder.mean_encoder.apply(weights_init)
            self.z_encoder.var_encoder.apply(weights_init)
            self.decoder.px_decoder.fc_layers.apply(weights_init)`
