### ISSUE TITLE
scvi - refactor the NB distribution

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#148]
For now we have copied and pasted way too much code from scvi-tools when it comes to the negative binomial distribution.

Get rid of a lot of that code.

Only keep what is necessary.

Also, @mbabadi has pointed out 
> This is not robust when theta is large, see cellarium-gpt branch.

Let's leverage the NB distribution that's already been written by @ordabayevy on the cellarium-gpt branch and get rid of all the scvi-tools copy and paste.

**Comment by ImXman** [comment]
Reviewed. No comments
