### ISSUE TITLE
scvi - come up with a test dataset and test current code

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#149]
Work with @fedorgrab to create a data extract from the Cellarium data repo that has just a few batches of PBMC data.

Point to those extracted h5ad files in the scvi config file.

Run our scvi from the `modified_scvi` branch.

Post the results here.  Is it currently working?

**Comment by ImXman** [comment]
test data
UMAP colored by batch
![Image](https://github.com/cellarium-ai/cellarium-ml/assets/35667575/25f3e3a7-5b07-47af-9d87-45fd2466b833)

UMAP colored by cell type
![Image](https://github.com/cellarium-ai/cellarium-ml/assets/35667575/7760f534-8a40-4cb9-a944-c4e635550423)
