### ISSUE TITLE
Enable geneformer in silico perturbations

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#97]
The idea would be to allow us to easily do _in silico_ perturbation experiments using trained transformer models.  For an example, see the Theodoris geneformer paper's Methods section on "In silico perturbation".

I think this can naturally fit into the `.predict()` function.  It is something we want to do using a trained model.  And I think it fits into the predict functionality without adding too much code to that function.

**Comment by ordabayevy** [comment]
Closed via #98
